// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAFklbnKCo07ByMU_Li3GCRlwwvJzTiuDc',
    appId: '1:808648894458:web:28c2c758ed2878ce05e643',
    messagingSenderId: '808648894458',
    projectId: 'doctorappointmentapp-ade49',
    authDomain: 'doctorappointmentapp-ade49.firebaseapp.com',
    storageBucket: 'doctorappointmentapp-ade49.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDd1n7-FuyOkBFKf1md2NJNjisNN1gTR0A',
    appId: '1:808648894458:android:7488e8222ffafe5405e643',
    messagingSenderId: '808648894458',
    projectId: 'doctorappointmentapp-ade49',
    storageBucket: 'doctorappointmentapp-ade49.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB5s_gCviWEJiQVycIrZb-40z4MRuh7SVQ',
    appId: '1:808648894458:ios:d83863682edb976c05e643',
    messagingSenderId: '808648894458',
    projectId: 'doctorappointmentapp-ade49',
    storageBucket: 'doctorappointmentapp-ade49.firebasestorage.app',
    iosBundleId: 'com.example.docktorAppointmentApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB5s_gCviWEJiQVycIrZb-40z4MRuh7SVQ',
    appId: '1:808648894458:ios:d83863682edb976c05e643',
    messagingSenderId: '808648894458',
    projectId: 'doctorappointmentapp-ade49',
    storageBucket: 'doctorappointmentapp-ade49.firebasestorage.app',
    iosBundleId: 'com.example.docktorAppointmentApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAFklbnKCo07ByMU_Li3GCRlwwvJzTiuDc',
    appId: '1:808648894458:web:a7301fa3a2e8b1cd05e643',
    messagingSenderId: '808648894458',
    projectId: 'doctorappointmentapp-ade49',
    authDomain: 'doctorappointmentapp-ade49.firebaseapp.com',
    storageBucket: 'doctorappointmentapp-ade49.firebasestorage.app',
  );
}
